function getCategoriesJSONList() {
	var categoriesLIST = new Array();
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,General");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Americana");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Art");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Autographs");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Automobiles see Transportation");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Books");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Bottles");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Buttons & Pins");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Canadiana");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Care & Restoration");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Cars see Transportation");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Ceramics see Pottery & Ceramics");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,China see Porcelain & China");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Clocks & Watches");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Coins  Currency & Medals");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Comics");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Costume see Textiles & Costume");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Dance see Performing Arts");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Disneyana see Americana");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Dolls");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Figurines");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Firearms & Weapons");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Furniture");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Glass & Glassware");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Gold see Silver  Gold & Other Metals");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Hummels see Figurines or Popular Culture");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Jewelry");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Kitchenware");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Magazines & Newspapers");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Medals see Coins  Currency & Medals");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Military");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Movies see Performing Arts");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Musical Instruments see Performing Arts");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Nautical see Transportation");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Newspapers see Magazines & Newspapers");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Non-Sports Cards");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Paper Ephemera");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Performing Arts");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Pewter see Silver  Gold & Other Metals");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Political");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Popular Culture");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Porcelain & China");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Postcards");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Posters");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Pottery & Ceramics");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Radios & Televisions (see alsoPerforming Arts)");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Records");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Reference");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Restoration see Care & Restoration");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Royalty see Popular Culture");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Rugs");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Silver  Gold & Other Metals");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Sports (see also headings underSports Cards)");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Sports Cards,General");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Sports Cards,Baseball");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Stained Glass see Glass & Glassware");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Stamps");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Teddy Bears");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Televisions & Television-Related seePerforming Arts or Radios & Televisions");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Textiles & Costume");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Theater see Performing Arts");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Tobacco-Related");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Toy Animals");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Toys");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Transportation");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Watches see Clocks & Watches");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Weapons see Firearms & Weapons");
	categoriesLIST.push("ANTIQUES & COLLECTIBLES,Wine");
	categoriesLIST.push("ARCHITECTURE,General");
	categoriesLIST.push("ARCHITECTURE,Adaptive Reuse & Renovation");
	categoriesLIST.push("ARCHITECTURE,Annuals");
	categoriesLIST.push("ARCHITECTURE,Buildings,General");
	categoriesLIST.push("ARCHITECTURE,Buildings,Landmarks & Monuments");
	categoriesLIST.push("ARCHITECTURE,Buildings,Public  Commercial & Industrial");
	categoriesLIST.push("ARCHITECTURE,Buildings,Religious");
	categoriesLIST.push("ARCHITECTURE,Buildings,Residential");
	categoriesLIST.push("ARCHITECTURE,CAD (Computer Aided Design) see Design  Drafting  Drawing & Presentation");
	categoriesLIST.push("ARCHITECTURE,Codes & Standards");
	categoriesLIST.push("ARCHITECTURE,Criticism");
	categoriesLIST.push("ARCHITECTURE,Decoration & Ornament");
	categoriesLIST.push("ARCHITECTURE,Design  Drafting  Drawing & Presentation");
	categoriesLIST.push("ARCHITECTURE,Feng Shui see BODY  MIND & SPIRIT,Feng Shui");
	categoriesLIST.push("ARCHITECTURE,Historic Preservation,General");
	categoriesLIST.push("ARCHITECTURE,Historic Preservation,Restoration Techniques");
	categoriesLIST.push("ARCHITECTURE,History,General");
	categoriesLIST.push("ARCHITECTURE,History,Prehistoric & Primitive");
	categoriesLIST.push("ARCHITECTURE,History,Ancient & Classical");
	categoriesLIST.push("ARCHITECTURE,History,Medieval");
	categoriesLIST.push("ARCHITECTURE,History,Renaissance");
	categoriesLIST.push("ARCHITECTURE,History,Baroque & Rococo");
	categoriesLIST.push("ARCHITECTURE,History,Romanticism");
	categoriesLIST.push("ARCHITECTURE,History,Modern (late 19th Century to 1945)");
	categoriesLIST.push("ARCHITECTURE,History,Contemporary (1945-)");
	categoriesLIST.push("ARCHITECTURE,Individual Architects & Firms,General");
	categoriesLIST.push("ARCHITECTURE,Individual Architects & Firms,Essays");
	categoriesLIST.push("ARCHITECTURE,Individual Architects & Firms,Monographs");
	categoriesLIST.push("ARCHITECTURE,Interior Design,General");
	categoriesLIST.push("ARCHITECTURE,Interior Design,Lighting");
	categoriesLIST.push("ARCHITECTURE,Landscape");
	categoriesLIST.push("ARCHITECTURE,Methods & Materials");
	categoriesLIST.push("ARCHITECTURE,Professional Practice");
	categoriesLIST.push("ARCHITECTURE,Project Management");
	categoriesLIST.push("ARCHITECTURE,Reference");
	categoriesLIST.push("ARCHITECTURE,Regional");
	categoriesLIST.push("ARCHITECTURE,Security Design");
	categoriesLIST.push("ARCHITECTURE,Study & Teaching");
	categoriesLIST.push("ARCHITECTURE,Sustainability & Green Design");
	categoriesLIST.push("ARCHITECTURE,Urban & Land Use Planning");
	categoriesLIST.push("ART,General");
	categoriesLIST.push("ART,African");
	categoriesLIST.push("ART,American,General");
	categoriesLIST.push("ART,American,African American");
	categoriesLIST.push("ART,American,Asian American");
	categoriesLIST.push("ART,American,Hispanic American");
	categoriesLIST.push("ART,Animation see PERFORMING ARTS,Animation");
	categoriesLIST.push("ART,Annuals");
	categoriesLIST.push("ART,Art & Politics");
	categoriesLIST.push("ART,Asian");
	categoriesLIST.push("ART,Australian & Oceanian");
	categoriesLIST.push("ART,Basic Techniques see headings under Techniques");
	categoriesLIST.push("ART,Body Art & Tattooing");
	categoriesLIST.push("ART,Book Design see DESIGN,Book");
	categoriesLIST.push("ART,Business Aspects");
	categoriesLIST.push("ART,Canadian");
	categoriesLIST.push("ART,Caribbean & Latin American");
	categoriesLIST.push("ART,Ceramics");
	categoriesLIST.push("ART,Collections  Catalogs  Exhibitions,General");
	categoriesLIST.push("ART,Collections  Catalogs  Exhibitions,Group Shows");
	categoriesLIST.push("ART,Collections  Catalogs  Exhibitions,Permanent Collections");
	categoriesLIST.push("ART,Color Theory");
	categoriesLIST.push("ART,Conceptual");
	categoriesLIST.push("ART,Conservation & Preservation");
	categoriesLIST.push("ART,Costume Design see DESIGN,Textile & Costume");
	categoriesLIST.push("ART,Criticism & Theory");
	categoriesLIST.push("ART,Design see headings under DESIGN");
	categoriesLIST.push("ART,Digital");
	categoriesLIST.push("ART,Exhibitions see headings under Collections  Catalogs  Exhibitions");
	categoriesLIST.push("ART,European");
	categoriesLIST.push("ART,Film & Video");
	categoriesLIST.push("ART,Folk & Outsider Art");
	categoriesLIST.push("ART,Furniture Design see DESIGN,Furniture");
	categoriesLIST.push("ART,Graffiti & Street Art");
	categoriesLIST.push("ART,History,General");
	categoriesLIST.push("ART,History,Prehistoric & Primitive");
	categoriesLIST.push("ART,History,Ancient & Classical");
	categoriesLIST.push("ART,History,Medieval");
	categoriesLIST.push("ART,History,Renaissance");
	categoriesLIST.push("ART,History,Baroque & Rococo");
	categoriesLIST.push("ART,History,Romanticism");
	categoriesLIST.push("ART,History,Modern (late 19th Century to 1945)");
	categoriesLIST.push("ART,History,Contemporary (1945-)");
	categoriesLIST.push("ART,Individual Artists,General");
	categoriesLIST.push("ART,Individual Artists,Artists' Books");
	categoriesLIST.push("ART,Individual Artists,Essays");
	categoriesLIST.push("ART,Individual Artists,Monographs");
	categoriesLIST.push("ART,Latin American see Caribbean & Latin American");
	categoriesLIST.push("ART,Middle Eastern");
	categoriesLIST.push("ART,Mixed Media");
	categoriesLIST.push("ART,Museum Administration & Museology see BUSINESS & ECONOMICS,Museum Administration & Museology");
	categoriesLIST.push("ART,Museum Studies");
	categoriesLIST.push("ART,Native American");
	categoriesLIST.push("ART,Oceanian see Australian & Oceanian");
	categoriesLIST.push("ART,Oriental see Asian");
	categoriesLIST.push("ART,Performance");
	categoriesLIST.push("ART,Popular Culture");
	categoriesLIST.push("ART,Prints");
	categoriesLIST.push("ART,Product Design see DESIGN,Product");
	categoriesLIST.push("ART,Reference");
	categoriesLIST.push("ART,Russian & Former Soviet Union");
	categoriesLIST.push("ART,Sculpture & Installation");
	categoriesLIST.push("ART,Study & Teaching");
	categoriesLIST.push("ART,Subjects & Themes,General");
	categoriesLIST.push("ART,Subjects & Themes,Erotica");
	categoriesLIST.push("ART,Subjects & Themes,Human Figure");
	categoriesLIST.push("ART,Subjects & Themes,Landscapes & Seascapes");
	categoriesLIST.push("ART,Subjects & Themes,Plants & Animals");
	categoriesLIST.push("ART,Subjects & Themes,Portraits");
	categoriesLIST.push("ART,Subjects & Themes,Religious");
	categoriesLIST.push("ART,Subjects & Themes,Science Fiction & Fantasy *");
	categoriesLIST.push("ART,Techniques,General");
	categoriesLIST.push("ART,Techniques,Acrylic Painting");
	categoriesLIST.push("ART,Techniques,Airbrush");
	categoriesLIST.push("ART,Techniques,Calligraphy");
	categoriesLIST.push("ART,Techniques,Cartooning");
	categoriesLIST.push("ART,Techniques,Color");
	categoriesLIST.push("ART,Techniques,Drawing");
	categoriesLIST.push("ART,Techniques,Life Drawing");
	categoriesLIST.push("ART,Techniques,Oil Painting");
	categoriesLIST.push("ART,Techniques,Painting");
	categoriesLIST.push("ART,Techniques,Pastel Drawing");
	categoriesLIST.push("ART,Techniques,Pen & Ink Drawing");
	categoriesLIST.push("ART,Techniques,Pencil Drawing");
	categoriesLIST.push("ART,Techniques,Printmaking");
	categoriesLIST.push("ART,Techniques,Sculpting");
	categoriesLIST.push("ART,Techniques,Watercolor Painting");
	categoriesLIST.push("ART,Textile Design see DESIGN,Textile & Costume");
	categoriesLIST.push("ART,Video see Film & Video");
	categoriesLIST.push("BIBLES,General");
	categoriesLIST.push("BIBLES,Christian Standard Bible,General");
	categoriesLIST.push("BIBLES,Christian Standard Bible,Children");
	categoriesLIST.push("BIBLES,Christian Standard Bible,Devotional");
	categoriesLIST.push("BIBLES,Christian Standard Bible,New Testament & Portions");
	categoriesLIST.push("BIBLES,Christian Standard Bible,Reference");
	categoriesLIST.push("BIBLES,Christian Standard Bible,Study");
	categoriesLIST.push("BIBLES,Christian Standard Bible,Text");
	categoriesLIST.push("BIBLES,Christian Standard Bible,Youth & Teen");
	categoriesLIST.push("BIBLES,Common English Bible,General");
	categoriesLIST.push("BIBLES,Common English Bible,Children");
	categoriesLIST.push("BIBLES,Common English Bible,Devotional");
	categoriesLIST.push("BIBLES,Common English Bible,New Testament & Portions");
	categoriesLIST.push("BIBLES,Common English Bible,Reference");
	categoriesLIST.push("BIBLES,Common English Bible,Study");
	categoriesLIST.push("BIBLES,Common English Bible,Text");
	categoriesLIST.push("BIBLES,Common English Bible,Youth & Teen");
	categoriesLIST.push("BIBLES,Contemporary English Version,General");
	categoriesLIST.push("BIBLES,Contemporary English Version,Children");
	categoriesLIST.push("BIBLES,Contemporary English Version,Devotional");
	categoriesLIST.push("BIBLES,Contemporary English Version,New Testament & Portions");
	categoriesLIST.push("BIBLES,Contemporary English Version,Reference");
	categoriesLIST.push("BIBLES,Contemporary English Version,Study");
	categoriesLIST.push("BIBLES,Contemporary English Version,Text");
	categoriesLIST.push("BIBLES,Contemporary English Version,Youth & Teen");
	categoriesLIST.push("BIBLES,English Standard Version,General");
	categoriesLIST.push("BIBLES,English Standard Version,Children");
	categoriesLIST.push("BIBLES,English Standard Version,Devotional");
	categoriesLIST.push("BIBLES,English Standard Version,New Testament & Portions");
	categoriesLIST.push("BIBLES,English Standard Version,Reference");
	categoriesLIST.push("BIBLES,English Standard Version,Study");
	categoriesLIST.push("BIBLES,English Standard Version,Text");
	categoriesLIST.push("BIBLES,English Standard Version,Youth & Teen");
	categoriesLIST.push("BIBLES,God's Word,General");
	categoriesLIST.push("BIBLES,God's Word,Children");
	categoriesLIST.push("BIBLES,God's Word,Devotional");
	categoriesLIST.push("BIBLES,God's Word,New Testament & Portions");
	categoriesLIST.push("BIBLES,God's Word,Reference");
	categoriesLIST.push("BIBLES,God's Word,Study");
	categoriesLIST.push("BIBLES,God's Word,Text");
	categoriesLIST.push("BIBLES,God's Word,Youth & Teen");
	categoriesLIST.push("BIBLES,International Children's Bible,General");
	categoriesLIST.push("BIBLES,International Children's Bible,Children");
	categoriesLIST.push("BIBLES,International Children's Bible,Devotional");
	categoriesLIST.push("BIBLES,International Children's Bible,New Testament & Portions");
	categoriesLIST.push("BIBLES,International Children's Bible,Reference");
	categoriesLIST.push("BIBLES,International Children's Bible,Study");
	categoriesLIST.push("BIBLES,International Children's Bible,Text");
	categoriesLIST.push("BIBLES,International Children's Bible,Youth & Teen");
	categoriesLIST.push("BIBLES,King James Version,General");
	categoriesLIST.push("BIBLES,King James Version,Children");
	categoriesLIST.push("BIBLES,King James Version,Devotional");
	categoriesLIST.push("BIBLES,King James Version,New Testament & Portions");
	categoriesLIST.push("BIBLES,King James Version,Reference");
	categoriesLIST.push("BIBLES,King James Version,Study");
	categoriesLIST.push("BIBLES,King James Version,Text");
	categoriesLIST.push("BIBLES,King James Version,Youth & Teen");
	categoriesLIST.push("BIBLES,La Biblia de las Americas,General");
	categoriesLIST.push("BIBLES,La Biblia de las Americas,Children");
	categoriesLIST.push("BIBLES,La Biblia de las Americas,Devotional");
	categoriesLIST.push("BIBLES,La Biblia de las Americas,New Testament & Portions");
	categoriesLIST.push("BIBLES,La Biblia de las Americas,Reference");
	categoriesLIST.push("BIBLES,La Biblia de las Americas,Study");
	categoriesLIST.push("BIBLES,La Biblia de las Americas,Text");
	categoriesLIST.push("BIBLES,La Biblia de las Americas,Youth & Teen");
	categoriesLIST.push("BIBLES,Multiple Translations,General");
	categoriesLIST.push("BIBLES,Multiple Translations,Children");
	categoriesLIST.push("BIBLES,Multiple Translations,Devotional");
	categoriesLIST.push("BIBLES,Multiple Translations,New Testament & Portions");
	categoriesLIST.push("BIBLES,Multiple Translations,Reference");
	categoriesLIST.push("BIBLES,Multiple Translations,Study");
	categoriesLIST.push("BIBLES,Multiple Translations,Text");
	categoriesLIST.push("BIBLES,Multiple Translations,Youth & Teen");
	categoriesLIST.push("BIBLES,New American Bible,General");
	categoriesLIST.push("BIBLES,New American Bible,Children");
	categoriesLIST.push("BIBLES,New American Bible,Devotional");
	categoriesLIST.push("BIBLES,New American Bible,New Testament & Portions");
	categoriesLIST.push("BIBLES,New American Bible,Reference");
	categoriesLIST.push("BIBLES,New American Bible,Study");
	categoriesLIST.push("BIBLES,New American Bible,Text");
	categoriesLIST.push("BIBLES,New American Bible,Youth & Teen");
	categoriesLIST.push("BIBLES,New American Standard Bible,General");
	categoriesLIST.push("BIBLES,New American Standard Bible,Children");
	categoriesLIST.push("BIBLES,New American Standard Bible,Devotional");
	categoriesLIST.push("BIBLES,New American Standard Bible,New Testament & Portions");
	categoriesLIST.push("BIBLES,New American Standard Bible,Reference");
	categoriesLIST.push("BIBLES,New American Standard Bible,Study");
	categoriesLIST.push("BIBLES,New American Standard Bible,Text");
	categoriesLIST.push("BIBLES,New American Standard Bible,Youth & Teen");
	categoriesLIST.push("BIBLES,New Century Version,General");
	categoriesLIST.push("BIBLES,New Century Version,Children");
	categoriesLIST.push("BIBLES,New Century Version,Devotional");
	categoriesLIST.push("BIBLES,New Century Version,New Testament & Portions");
	categoriesLIST.push("BIBLES,New Century Version,Reference");
	categoriesLIST.push("BIBLES,New Century Version,Study");
	categoriesLIST.push("BIBLES,New Century Version,Text");
	categoriesLIST.push("BIBLES,New Century Version,Youth & Teen");
	categoriesLIST.push("BIBLES,New International Reader's Version,General");
	categoriesLIST.push("BIBLES,New International Reader's Version,Children");
	categoriesLIST.push("BIBLES,New International Reader's Version,Devotional");
	categoriesLIST.push("BIBLES,New International Reader's Version,New Testament & Portions");
	categoriesLIST.push("BIBLES,New International Reader's Version,Reference");
	categoriesLIST.push("BIBLES,New International Reader's Version,Study");
	categoriesLIST.push("BIBLES,New International Reader's Version,Text");
	categoriesLIST.push("BIBLES,New International Reader's Version,Youth & Teen");
	categoriesLIST.push("BIBLES,New International Version,General");
	categoriesLIST.push("BIBLES,New International Version,Children");
	categoriesLIST.push("BIBLES,New International Version,Devotional");
	categoriesLIST.push("BIBLES,New International Version,New Testament & Portions");
	categoriesLIST.push("BIBLES,New International Version,Reference");
	categoriesLIST.push("BIBLES,New International Version,Study");
	categoriesLIST.push("BIBLES,New International Version,Text");
	categoriesLIST.push("BIBLES,New International Version,Youth & Teen");
	categoriesLIST.push("BIBLES,New King James Version,General");
	categoriesLIST.push("BIBLES,New King James Version,Children");
	categoriesLIST.push("BIBLES,New King James Version,Devotional");
	categoriesLIST.push("BIBLES,New King James Version,New Testament & Portions");
	categoriesLIST.push("BIBLES,New King James Version,Reference");
	categoriesLIST.push("BIBLES,New King James Version,Study");
	categoriesLIST.push("BIBLES,New King James Version,Text");
	categoriesLIST.push("BIBLES,New King James Version,Youth & Teen");
	categoriesLIST.push("BIBLES,New Living Translation,General");
	categoriesLIST.push("BIBLES,New Living Translation,Children");
	categoriesLIST.push("BIBLES,New Living Translation,Devotional");
	categoriesLIST.push("BIBLES,New Living Translation,New Testament & Portions");
	categoriesLIST.push("BIBLES,New Living Translation,Reference");
	categoriesLIST.push("BIBLES,New Living Translation,Study");
	categoriesLIST.push("BIBLES,New Living Translation,Text");
	categoriesLIST.push("BIBLES,New Living Translation,Youth & Teen");
	categoriesLIST.push("BIBLES,New Revised Standard Version,General");
	categoriesLIST.push("BIBLES,New Revised Standard Version,Children");
	categoriesLIST.push("BIBLES,New Revised Standard Version,Devotional");
	categoriesLIST.push("BIBLES,New Revised Standard Version,New Testament & Portions");
	categoriesLIST.push("BIBLES,New Revised Standard Version,Reference");
	categoriesLIST.push("BIBLES,New Revised Standard Version,Study");
	categoriesLIST.push("BIBLES,New Revised Standard Version,Text");
	categoriesLIST.push("BIBLES,New Revised Standard Version,Youth & Teen");
	categoriesLIST.push("BIBLES,Nueva Version International,General");
	categoriesLIST.push("BIBLES,Nueva Version International,Children");
	categoriesLIST.push("BIBLES,Nueva Version International,Devotional");
	categoriesLIST.push("BIBLES,Nueva Version International,New Testament & Portions");
	categoriesLIST.push("BIBLES,Nueva Version International,Reference");
	categoriesLIST.push("BIBLES,Nueva Version International,Study");
	categoriesLIST.push("BIBLES,Nueva Version International,Text");
	categoriesLIST.push("BIBLES,Nueva Version International,Youth & Teen");
	categoriesLIST.push("BIBLES,Other Translations,General");
	categoriesLIST.push("BIBLES,Other Translations,Children");
	categoriesLIST.push("BIBLES,Other Translations,Devotional");
	categoriesLIST.push("BIBLES,Other Translations,New Testament & Portions");
	categoriesLIST.push("BIBLES,Other Translations,Reference");
	categoriesLIST.push("BIBLES,Other Translations,Study");
	categoriesLIST.push("BIBLES,Other Translations,Text");
	categoriesLIST.push("BIBLES,Other Translations,Youth & Teen");
	categoriesLIST.push("BIBLES,Reina Valera,General");
	categoriesLIST.push("BIBLES,Reina Valera,Children");
	categoriesLIST.push("BIBLES,Reina Valera,Devotional");
	categoriesLIST.push("BIBLES,Reina Valera,New Testament & Portions");
	categoriesLIST.push("BIBLES,Reina Valera,Reference");
	categoriesLIST.push("BIBLES,Reina Valera,Study");
	categoriesLIST.push("BIBLES,Reina Valera,Text");
	categoriesLIST.push("BIBLES,Reina Valera,Youth & Teen");
	categoriesLIST.push("BIBLES,The Amplified Bible,General *");
	categoriesLIST.push("BIBLES,The Amplified Bible,Children *");
	categoriesLIST.push("BIBLES,The Amplified Bible,Devotional *");
	categoriesLIST.push("BIBLES,The Amplified Bible,New Testament & Portions *");
	categoriesLIST.push("BIBLES,The Amplified Bible,Reference *");
	categoriesLIST.push("BIBLES,The Amplified Bible,Study *");
	categoriesLIST.push("BIBLES,The Amplified Bible,Text *");
	categoriesLIST.push("BIBLES,The Amplified Bible,Youth & Teen *");
	categoriesLIST.push("BIBLES,The Message,General");
	categoriesLIST.push("BIBLES,The Message,Children");
	categoriesLIST.push("BIBLES,The Message,Devotional");
	categoriesLIST.push("BIBLES,The Message,New Testament & Portions");
	categoriesLIST.push("BIBLES,The Message,Reference");
	categoriesLIST.push("BIBLES,The Message,Study");
	categoriesLIST.push("BIBLES,The Message,Text");
	categoriesLIST.push("BIBLES,The Message,Youth & Teen");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,General");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Adventurers & Explorers");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,African American & Black seeCultural Heritage");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Artists  Architects  Photographers");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Business");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Composers & Musicians");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Criminals & Outlaws");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Culinary");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Cultural Heritage");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Doctors see Medical");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Editors  Journalists  Publishers");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Educators");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Entertainment & Performing Arts");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Environmentalists & Naturalists");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Famous see Rich & Famous");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Historical");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Judges see Lawyers & Judges");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Law Enforcement");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Lawyers & Judges");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,LGBT");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Literary");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Medical");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Military");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Musicians see Composers & Musicians");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Native Americans");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Nurses see Medical");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,People with Disabilities ");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Performing Arts see Entertainment & Performing Arts");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Personal Memoirs");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Philosophers");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Photographers see Artists  Architects  Photographers");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Physicians see Medical");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Political");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Presidents & Heads of State");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Psychologists see Social Scientists & Psychologists");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Reference");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Religious");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Rich & Famous");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Royalty");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Science & Technology");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Social Activists");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Social Scientists & Psychologists");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Sports");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Surgeons see Medical");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Teachers see Educators");
	categoriesLIST.push("BIOGRAPHY & AUTOBIOGRAPHY,Women");
	categoriesLIST.push("BODY  MIND & SPIRIT,General");
	categoriesLIST.push("BODY  MIND & SPIRIT,Afterlife & Reincarnation");
	categoriesLIST.push("BODY  MIND & SPIRIT,Ancient Mysteries & Controversial Knowledge");
	categoriesLIST.push("BODY  MIND & SPIRIT,Angels & Spirit Guides");
	categoriesLIST.push("BODY  MIND & SPIRIT,Astrology,General");
	categoriesLIST.push("BODY  MIND & SPIRIT,Astrology,Eastern");
	categoriesLIST.push("BODY  MIND & SPIRIT,Astrology,Horoscopes");
	categoriesLIST.push("BODY  MIND & SPIRIT,Celtic Spirituality");
	categoriesLIST.push("BODY  MIND & SPIRIT,Channeling & Mediumship");
	categoriesLIST.push("BODY  MIND & SPIRIT,Crystals");
	categoriesLIST.push("BODY  MIND & SPIRIT,Divination,General");
	categoriesLIST.push("BODY  MIND & SPIRIT,Divination,Fortune Telling");
	categoriesLIST.push("BODY  MIND & SPIRIT,Divination,Palmistry");
	categoriesLIST.push("BODY  MIND & SPIRIT,Divination,Tarot");
	categoriesLIST.push("BODY  MIND & SPIRIT,Dowsing see Divination,General");
	categoriesLIST.push("BODY  MIND & SPIRIT,Dreams");
	categoriesLIST.push("BODY  MIND & SPIRIT,Entheogens & Visionary Substances");
	categoriesLIST.push("BODY  MIND & SPIRIT,Feng Shui");
	categoriesLIST.push("BODY  MIND & SPIRIT,Gaia & Earth Energies");
	categoriesLIST.push("BODY  MIND & SPIRIT,Gnosticism see RELIGION,Gnosticism");
	categoriesLIST.push("BODY  MIND & SPIRIT,Goddess Worship");
	categoriesLIST.push("BODY  MIND & SPIRIT,Healing,General");
	categoriesLIST.push("BODY  MIND & SPIRIT,Healing,Energy (Qigong  Reiki  Polarity)");
	categoriesLIST.push("BODY  MIND & SPIRIT,Healing,Prayer & Spiritual");
	categoriesLIST.push("BODY  MIND & SPIRIT,Hermetism & Rosicrucianism");
	categoriesLIST.push("BODY  MIND & SPIRIT,I Ching");
	categoriesLIST.push("BODY  MIND & SPIRIT,Inspiration & Personal Growth");
	categoriesLIST.push("BODY  MIND & SPIRIT,Magick Studies");
	categoriesLIST.push("BODY  MIND & SPIRIT,Mindfulness & Meditation");
	categoriesLIST.push("BODY  MIND & SPIRIT,Mysticism");
	categoriesLIST.push("BODY  MIND & SPIRIT,New Age see General");
	categoriesLIST.push("BODY  MIND & SPIRIT,New Thought");
	categoriesLIST.push("BODY  MIND & SPIRIT,Numerology");
	categoriesLIST.push("BODY  MIND & SPIRIT,Occultism");
	categoriesLIST.push("BODY  MIND & SPIRIT,Paganism & Neo-Paganism see RELIGION,Paganism & Neo-Paganism");
	categoriesLIST.push("BODY  MIND & SPIRIT,Parapsychology,General");
	categoriesLIST.push("BODY  MIND & SPIRIT,Parapsychology,ESP (Clairvoyance  Precognition  Telepathy)");
	categoriesLIST.push("BODY  MIND & SPIRIT,Parapsychology,Near-Death Experience");
	categoriesLIST.push("BODY  MIND & SPIRIT,Parapsychology,Out-of-Body Experience");
	categoriesLIST.push("BODY  MIND & SPIRIT,Prophecy");
	categoriesLIST.push("BODY  MIND & SPIRIT,Psychic Phenomena see headings underParapsychology");
	categoriesLIST.push("BODY  MIND & SPIRIT,Reference");
	categoriesLIST.push("BODY  MIND & SPIRIT,Sacred Sexuality");
	categoriesLIST.push("BODY  MIND & SPIRIT,Shamanism");
	categoriesLIST.push("BODY  MIND & SPIRIT,Spiritual Healing see Healing,Prayer & Spiritual");
	categoriesLIST.push("BODY  MIND & SPIRIT,Spiritualism");
	categoriesLIST.push("BODY  MIND & SPIRIT,Supernatural");
	categoriesLIST.push("BODY  MIND & SPIRIT,UFOs & Extraterrestrials");
	categoriesLIST.push("BODY  MIND & SPIRIT,Unexplained Phenomena");
	categoriesLIST.push("BODY  MIND & SPIRIT,Witchcraft (see also RELIGION,Wicca)");
	categoriesLIST.push("BODY  MIND & SPIRIT,Yoga see HEALTH & FITNESS,Yoga");
	categoriesLIST.push("BODY  MIND & SPIRIT,Zen Buddhism see PHILOSOPHY,Zen orRELIGION,Buddhism,Zen");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,General");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Adaptations ");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Anthologies");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Comics & Cartoons see HUMOR,Form,Comic Strips & Cartoons");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Contemporary Women");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Crime & Mystery");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Dystopian *");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Erotica");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Fantasy");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Historical Fiction");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Horror");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Juvenile Fiction see headings underJUVENILE FICTION,Comics & Graphic Novels");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Juvenile Nonfiction see headings under JUVENILE NONFICTION,Comics & Graphic Novels");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,LGBT");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Literary");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Manga,General");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Manga,Crime & Mystery");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Manga,Dystopian *");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Manga,Erotica & Hentai");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Manga,Fantasy");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Manga,Historical Fiction");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Manga,Horror");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Manga,LGBT");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Manga,Media Tie-In");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Manga,Nonfiction");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Manga,Romance");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Manga,Science Fiction");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Manga,Sports");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Manga,Yaoi");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Media Tie-In");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Nonfiction");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Religious");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Romance");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Science Fiction");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Superheroes");
	categoriesLIST.push("COMICS & GRAPHIC NOVELS,Techniques see ART,Techniques,Cartooning");
	categoriesLIST.push("COMPUTERS,General");
	categoriesLIST.push("COMPUTERS,Bioinformatics");
	categoriesLIST.push("COMPUTERS,Business Software see Enterprise Applications,Business Intelligence Tools");
	categoriesLIST.push("COMPUTERS,Buyer's Guides");
	categoriesLIST.push("COMPUTERS,CAD-CAM");
	categoriesLIST.push("COMPUTERS,Calculators");
	categoriesLIST.push("COMPUTERS,CD-DVD Technology");
	categoriesLIST.push("COMPUTERS,Certification Guides,General");
	categoriesLIST.push("COMPUTERS,Certification Guides,A+");
	categoriesLIST.push("COMPUTERS,Certification Guides,MCSE");
	categoriesLIST.push("COMPUTERS,Client-Server Computing");
	categoriesLIST.push("COMPUTERS,Cloud Computing *");
	categoriesLIST.push("COMPUTERS,Compilers");
	categoriesLIST.push("COMPUTERS,Computer Engineering");
	categoriesLIST.push("COMPUTERS,Computer Graphics");
	categoriesLIST.push("COMPUTERS,Computer Industry see BUSINESS & ECONOMICS,Industries,Computers & Information Technology");
	categoriesLIST.push("COMPUTERS,Computer Literacy");
	categoriesLIST.push("COMPUTERS,Computer Science");
	categoriesLIST.push("COMPUTERS,Computer Simulation");
	categoriesLIST.push("COMPUTERS,Computer Viruses see Security,Viruses & Malware");
	categoriesLIST.push("COMPUTERS,Computer Vision & Pattern Recognition");
	categoriesLIST.push("COMPUTERS,Computerized Home & Entertainment");
	categoriesLIST.push("COMPUTERS,Cybernetics");
	categoriesLIST.push("COMPUTERS,Data Modeling & Design");
	categoriesLIST.push("COMPUTERS,Data Processing");
	categoriesLIST.push("COMPUTERS,Data Recovery see System Administration,Disaster & Recovery");
	categoriesLIST.push("COMPUTERS,Data Transmission Systems,General");
	categoriesLIST.push("COMPUTERS,Data Transmission Systems,Broadband");
	categoriesLIST.push("COMPUTERS,Data Transmission Systems,Electronic Data Interchange");
	categoriesLIST.push("COMPUTERS,Data Transmission Systems,Wireless");
	categoriesLIST.push("COMPUTERS,Data Visualization");
	categoriesLIST.push("COMPUTERS,Databases,General");
	categoriesLIST.push("COMPUTERS,Databases,Data Mining");
	categoriesLIST.push("COMPUTERS,Databases,Data Warehousing");
	categoriesLIST.push("COMPUTERS,Databases,Servers");
	categoriesLIST.push("COMPUTERS,Desktop Applications,General");
	categoriesLIST.push("COMPUTERS,Desktop Applications,Databases");
	categoriesLIST.push("COMPUTERS,Desktop Applications,Design & Graphics");
	categoriesLIST.push("COMPUTERS,Desktop Applications,Desktop Publishing");
	categoriesLIST.push("COMPUTERS,Desktop Applications,Email Clients");
	categoriesLIST.push("COMPUTERS,Desktop Applications,Personal Finance Applications");
	categoriesLIST.push("COMPUTERS,Desktop Applications,Presentation Software");
	categoriesLIST.push("COMPUTERS,Desktop Applications,Project Management Software");
	categoriesLIST.push("COMPUTERS,Desktop Applications,Spreadsheets");
	categoriesLIST.push("COMPUTERS,Desktop Applications,Suites");
	categoriesLIST.push("COMPUTERS,Desktop Applications,Word Processing");
	categoriesLIST.push("COMPUTERS,Digital Media,General");
	categoriesLIST.push("COMPUTERS,Digital Media,Audio");
	categoriesLIST.push("COMPUTERS,Digital Media,Photography (see alsoPHOTOGRAPHY,Techniques,Digital)");
	categoriesLIST.push("COMPUTERS,Digital Media,Video & Animation");
	categoriesLIST.push("COMPUTERS,Document Management");
	categoriesLIST.push("COMPUTERS,Documentation & Technical Writing");
	categoriesLIST.push("COMPUTERS,Educational Software");
	categoriesLIST.push("COMPUTERS,Electronic Commerce (see also headings underBUSINESS & ECONOMICS,E-Commerce)");
	categoriesLIST.push("COMPUTERS,Electronic Publishing");
	categoriesLIST.push("COMPUTERS,Email see Desktop Applications,Email Clients or System Administration,Email Administration");
	categoriesLIST.push("COMPUTERS,Enterprise Applications,General");
	categoriesLIST.push("COMPUTERS,Enterprise Applications,Business Intelligence Tools");
	categoriesLIST.push("COMPUTERS,Enterprise Applications,Collaboration Software");
	categoriesLIST.push("COMPUTERS,Entertainment & Games see GAMES,Video & Electronic");
	categoriesLIST.push("COMPUTERS,Expert Systems");
	categoriesLIST.push("COMPUTERS,Financial Applications see Desktop Applications,Personal Finance Applications or Enterprise Applications,Business Intelligence Tools");
	categoriesLIST.push("COMPUTERS,Games see Programming,Games or GAMES,Video & Electronic");
	categoriesLIST.push("COMPUTERS,Hardware,General");
	categoriesLIST.push("COMPUTERS,Hardware,Mainframes & Minicomputers");
	categoriesLIST.push("COMPUTERS,Hardware,Mobile Devices");
	categoriesLIST.push("COMPUTERS,Hardware,Peripherals");
	categoriesLIST.push("COMPUTERS,Hardware,Personal Computers,General");
	categoriesLIST.push("COMPUTERS,Hardware,Personal Computers,Macintosh");
	categoriesLIST.push("COMPUTERS,Hardware,Personal Computers,PCs");
	categoriesLIST.push("COMPUTERS,Hardware,Tablets");
	categoriesLIST.push("COMPUTERS,History");
	categoriesLIST.push("COMPUTERS,Hypertext Systems see Programming Languages,HTML");
	categoriesLIST.push("COMPUTERS,Image Processing");
	categoriesLIST.push("COMPUTERS,Information Storage & Retrieval see System Administration,Storage & Retrieval");
	categoriesLIST.push("COMPUTERS,Information Technology");
	categoriesLIST.push("COMPUTERS,Information Theory");
	categoriesLIST.push("COMPUTERS,Input-Output Equipment see headings underHardware");
	categoriesLIST.push("COMPUTERS,Integrated Software see headings under Desktop Applications or headings under Enterprise Applications");
	categoriesLIST.push("COMPUTERS,Intelligence (AI) & Semantics");
	categoriesLIST.push("COMPUTERS,Interactive & Multimedia");
	categoriesLIST.push("COMPUTERS,Internet,General");
	categoriesLIST.push("COMPUTERS,Internet,Application Development");
	categoriesLIST.push("COMPUTERS,Internet,Commercial Use see Electronic Commerceor headings under BUSINESS & ECONOMICS,E-Commerce");
	categoriesLIST.push("COMPUTERS,Internet,Intranets see Networking,Intranets & Extranets");
	categoriesLIST.push("COMPUTERS,Internet,Server Maintenance see Hardware,Network Hardware");
	categoriesLIST.push("COMPUTERS,Keyboarding");
	categoriesLIST.push("COMPUTERS,Languages see headings under Programming Languages");
	categoriesLIST.push("COMPUTERS,Logic Design");
	categoriesLIST.push("COMPUTERS,Machine Theory");
	categoriesLIST.push("COMPUTERS,Mainframes & Minicomputers see Hardware,Mainframes & Minicomputers");
	categoriesLIST.push("COMPUTERS,Management Information Systems");
	categoriesLIST.push("COMPUTERS,Mathematical & Statistical Software");
	categoriesLIST.push("COMPUTERS,Microprocessors");
	categoriesLIST.push("COMPUTERS,Multimedia see Interactive & Multimedia");
	categoriesLIST.push("COMPUTERS,Natural Language Processing");
	categoriesLIST.push("COMPUTERS,Networking,General");
	categoriesLIST.push("COMPUTERS,Networking,Intranets & Extranets");
	categoriesLIST.push("COMPUTERS,Networking,Hardware");
	categoriesLIST.push("COMPUTERS,Networking,Local Area Networks (LANs)");
	categoriesLIST.push("COMPUTERS,Networking,Network Protocols");
	categoriesLIST.push("COMPUTERS,Networking,Security see Security,Networking");
	categoriesLIST.push("COMPUTERS,Networking,Vendor Specific");
	categoriesLIST.push("COMPUTERS,Neural Networks");
	categoriesLIST.push("COMPUTERS,Online Services");
	categoriesLIST.push("COMPUTERS,Operating Systems,General");
	categoriesLIST.push("COMPUTERS,Operating Systems,DOS");
	categoriesLIST.push("COMPUTERS,Operating Systems,Linux");
	categoriesLIST.push("COMPUTERS,Operating Systems,Macintosh");
	categoriesLIST.push("COMPUTERS,Operating Systems,Mainframe & Midrange");
	categoriesLIST.push("COMPUTERS,Operating Systems,UNIX");
	categoriesLIST.push("COMPUTERS,Operating Systems,Virtualization");
	categoriesLIST.push("COMPUTERS,Operating Systems,Windows Desktop");
	categoriesLIST.push("COMPUTERS,Operating Systems,Windows Server");
	categoriesLIST.push("COMPUTERS,Optical Data Processing");
	categoriesLIST.push("COMPUTERS,Parallel Processing see Systems Architecture,Distributed Systems & Computing");
	categoriesLIST.push("COMPUTERS,Peripherals see Hardware,Peripherals");
	categoriesLIST.push("COMPUTERS,Personal Computers & Microcomputers see headings under Hardware,Personal Computers");
	categoriesLIST.push("COMPUTERS,Programming,General");
	categoriesLIST.push("COMPUTERS,Programming,Algorithms");
	categoriesLIST.push("COMPUTERS,Programming,Games");
	categoriesLIST.push("COMPUTERS,Programming,Macintosh");
	categoriesLIST.push("COMPUTERS,Programming,Languages see headings underProgramming Languages");
	categoriesLIST.push("COMPUTERS,Programming,Microsoft");
	categoriesLIST.push("COMPUTERS,Programming,Mobile Devices");
	categoriesLIST.push("COMPUTERS,Programming,Object Oriented");
	categoriesLIST.push("COMPUTERS,Programming,Open Source");
	categoriesLIST.push("COMPUTERS,Programming,Parallel");
	categoriesLIST.push("COMPUTERS,Programming Languages,General");
	categoriesLIST.push("COMPUTERS,Programming Languages,Ada");
	categoriesLIST.push("COMPUTERS,Programming Languages,ASP .NET");
	categoriesLIST.push("COMPUTERS,Programming Languages,Assembly Language");
	categoriesLIST.push("COMPUTERS,Programming Languages,BASIC");
	categoriesLIST.push("COMPUTERS,Programming Languages,C");
	categoriesLIST.push("COMPUTERS,Programming Languages,C++");
	categoriesLIST.push("COMPUTERS,Programming Languages,C#");
	categoriesLIST.push("COMPUTERS,Programming Languages,COBOL");
	categoriesLIST.push("COMPUTERS,Programming Languages,FORTRAN");
	categoriesLIST.push("COMPUTERS,Programming Languages,HTML");
	categoriesLIST.push("COMPUTERS,Programming Languages,Java");
	categoriesLIST.push("COMPUTERS,Programming Languages,JavaScript");
	categoriesLIST.push("COMPUTERS,Programming Languages,LISP");
	categoriesLIST.push("COMPUTERS,Programming Languages,Pascal");
	categoriesLIST.push("COMPUTERS,Programming Languages,Perl");
	categoriesLIST.push("COMPUTERS,Programming Languages,PHP");
	categoriesLIST.push("COMPUTERS,Programming Languages,Prolog");
	categoriesLIST.push("COMPUTERS,Programming Languages,Python");
	categoriesLIST.push("COMPUTERS,Programming Languages,RPG");
	categoriesLIST.push("COMPUTERS,Programming Languages,Ruby");
	categoriesLIST.push("COMPUTERS,Programming Languages,SQL");
	categoriesLIST.push("COMPUTERS,Programming Languages,UML");
	categoriesLIST.push("COMPUTERS,Programming Languages,VBScript");
	categoriesLIST.push("COMPUTERS,Programming Languages,Visual BASIC");
	categoriesLIST.push("COMPUTERS,Programming Languages,XML");
	categoriesLIST.push("COMPUTERS,Reference");
	categoriesLIST.push("COMPUTERS,Security,General");
	categoriesLIST.push("COMPUTERS,Security,Cryptography");
	categoriesLIST.push("COMPUTERS,Security,Networking");
	categoriesLIST.push("COMPUTERS,Security,Online Safety & Privacy");
	categoriesLIST.push("COMPUTERS,Security,Viruses & Malware");
	categoriesLIST.push("COMPUTERS,Social Aspects,General");
	categoriesLIST.push("COMPUTERS,Social Aspects,Human-Computer Interaction");
	categoriesLIST.push("COMPUTERS,Software Development & Engineering,General");
	categoriesLIST.push("COMPUTERS,Software Development & Engineering,Project Management");
	categoriesLIST.push("COMPUTERS,Software Development & Engineering,Quality Assurance & Testing");
	categoriesLIST.push("COMPUTERS,Software Development & Engineering,Systems Analysis & Design");
	categoriesLIST.push("COMPUTERS,Software Development & Engineering,Tools");
	categoriesLIST.push("COMPUTERS,Speech & Audio Processing");
	categoriesLIST.push("COMPUTERS,System Administration,General");
	categoriesLIST.push("COMPUTERS,System Administration,Disaster & Recovery");
	categoriesLIST.push("COMPUTERS,System Administration,Email Administration");
	categoriesLIST.push("COMPUTERS,System Administration,Linux & UNIX Administration");
	categoriesLIST.push("COMPUTERS,System Administration,Storage & Retrieval");
	categoriesLIST.push("COMPUTERS,System Administration,Windows Administration");
	categoriesLIST.push("COMPUTERS,Systems Analysis see Software Development & Engineering,Systems Analysis & Design");
	categoriesLIST.push("COMPUTERS,Systems Architecture,General");
	categoriesLIST.push("COMPUTERS,Systems Architecture,Distributed Systems & Computing");
	categoriesLIST.push("COMPUTERS,User Interfaces");
	categoriesLIST.push("COMPUTERS,Utilities");
	categoriesLIST.push("COMPUTERS,Video Games see GAMES,Video & Electronic");
	categoriesLIST.push("COMPUTERS,Virtual Worlds");
	categoriesLIST.push("COMPUTERS,Viruses see Security,Viruses & Malware");
	categoriesLIST.push("COMPUTERS,Web,General");
	categoriesLIST.push("COMPUTERS,Web,Content Management Systems");
	categoriesLIST.push("COMPUTERS,Web,Design");
	categoriesLIST.push("COMPUTERS,Web,Blogs");
	categoriesLIST.push("COMPUTERS,Web,Browsers");
	categoriesLIST.push("COMPUTERS,Web,Podcasting & Webcasting");
	categoriesLIST.push("COMPUTERS,Web,Search Engines");
	categoriesLIST.push("COMPUTERS,Web,Site Directories");
	categoriesLIST.push("COMPUTERS,Web,Social Networking");
	categoriesLIST.push("COMPUTERS,Web,User Generated Content");
	categoriesLIST.push("COMPUTERS,Web,Web Programming");
	categoriesLIST.push("COMPUTERS,Web,Web Services & APIs");
	categoriesLIST.push("COOKING,General");
	categoriesLIST.push("COOKING,Baby Food");
	categoriesLIST.push("COOKING,Beverages,General");
	categoriesLIST.push("COOKING,Beverages,Bartending");
	categoriesLIST.push("COOKING,Beverages,Beer");
	categoriesLIST.push("COOKING,Beverages,Coffee & Tea");
	categoriesLIST.push("COOKING,Beverages,Juices & Smoothies *");
	categoriesLIST.push("COOKING,Beverages,Non-Alcoholic");
	categoriesLIST.push("COOKING,Beverages,Wine & Spirits");
	categoriesLIST.push("COOKING,Cigars & Tobacco see Entertaining or ANTIQUES & COLLECTIBLES,Tobacco-Related");
	categoriesLIST.push("COOKING,Cooking for Kids *");
	categoriesLIST.push("COOKING,Cooking with Kids *");
	categoriesLIST.push("COOKING,Courses & Dishes,General");
	categoriesLIST.push("COOKING,Courses & Dishes,Appetizers");
	categoriesLIST.push("COOKING,Courses & Dishes,Bread");
	categoriesLIST.push("COOKING,Courses & Dishes,Breakfast");
	categoriesLIST.push("COOKING,Courses & Dishes,Brunch & Tea Time");
	categoriesLIST.push("COOKING,Courses & Dishes,Cakes");
	categoriesLIST.push("COOKING,Courses & Dishes,Casseroles");
	categoriesLIST.push("COOKING,Courses & Dishes,Chocolate");
	categoriesLIST.push("COOKING,Courses & Dishes,Confectionery");
	categoriesLIST.push("COOKING,Courses & Dishes,Cookies");
	categoriesLIST.push("COOKING,Courses & Dishes,Desserts");
	categoriesLIST.push("COOKING,Courses & Dishes,Pastry");
	categoriesLIST.push("COOKING,Courses & Dishes,Pies");
	categoriesLIST.push("COOKING,Courses & Dishes,Pizza");
	categoriesLIST.push("COOKING,Courses & Dishes,Salads");
	categoriesLIST.push("COOKING,Courses & Dishes,Sandwiches *");
	categoriesLIST.push("COOKING,Courses & Dishes,Sauces & Dressings");
	categoriesLIST.push("COOKING,Courses & Dishes,Soups & Stews");
	categoriesLIST.push("COOKING,Entertaining");
	categoriesLIST.push("COOKING,Essays & Narratives");
	categoriesLIST.push("COOKING,Health & Healing,General");
	categoriesLIST.push("COOKING,Health & Healing,Allergy");
	categoriesLIST.push("COOKING,Health & Healing,Cancer");
	categoriesLIST.push("COOKING,Health & Healing,Diabetic & Sugar-Free");
	categoriesLIST.push("COOKING,Health & Healing,Gluten-Free");
	categoriesLIST.push("COOKING,Health & Healing,Heart");
	categoriesLIST.push("COOKING,Health & Healing,High Protein ");
	categoriesLIST.push("COOKING,Health & Healing,Low Carbohydrate");
	categoriesLIST.push("COOKING,Health & Healing,Low Cholesterol");
	categoriesLIST.push("COOKING,Health & Healing,Low Fat");
	categoriesLIST.push("COOKING,Health & Healing,Low Salt");
	categoriesLIST.push("COOKING,Health & Healing,Low Sugar see Health & Healing,Diabetic & Sugar-Free");
	categoriesLIST.push("COOKING,Health & Healing,Weight Control");
	categoriesLIST.push("COOKING,History");
	categoriesLIST.push("COOKING,Holiday");
	categoriesLIST.push("COOKING,Individual Chefs & Restaurants ");
	categoriesLIST.push("COOKING,Methods,General");
	categoriesLIST.push("COOKING,Methods,Baking");
	categoriesLIST.push("COOKING,Methods,Barbecue & Grilling");
	categoriesLIST.push("COOKING,Methods,Canning & Preserving");
	categoriesLIST.push("COOKING,Methods,Cookery for One");
	categoriesLIST.push("COOKING,Methods,Frying ");
	categoriesLIST.push("COOKING,Methods,Garnishing & Food Presentation");
	categoriesLIST.push("COOKING,Methods,Gourmet");
	categoriesLIST.push("COOKING,Methods,Low Budget");
	categoriesLIST.push("COOKING,Methods,Microwave");
	categoriesLIST.push("COOKING,Methods,Outdoor");
	categoriesLIST.push("COOKING,Methods,Professional");
	categoriesLIST.push("COOKING,Methods,Quantity");
	categoriesLIST.push("COOKING,Methods,Quick & Easy");
	categoriesLIST.push("COOKING,Methods,Raw Food");
	categoriesLIST.push("COOKING,Methods,Slow Cooking");
	categoriesLIST.push("COOKING,Methods,Special Appliances");
	categoriesLIST.push("COOKING,Methods,Wok");
	categoriesLIST.push("COOKING,Pet Food ");
	categoriesLIST.push("COOKING,Reference");
	categoriesLIST.push("COOKING,Regional & Ethnic,General");
	categoriesLIST.push("COOKING,Regional & Ethnic,African");
	categoriesLIST.push("COOKING,Regional & Ethnic,American,General");
	categoriesLIST.push("COOKING,Regional & Ethnic,American,California Style");
	categoriesLIST.push("COOKING,Regional & Ethnic,American,Middle Atlantic States");
	categoriesLIST.push("COOKING,Regional & Ethnic,American,Middle Western States");
	categoriesLIST.push("COOKING,Regional & Ethnic,American,New England");
	categoriesLIST.push("COOKING,Regional & Ethnic,American,Northwestern States");
	categoriesLIST.push("COOKING,Regional & Ethnic,American,Southern States");
	categoriesLIST.push("COOKING,Regional & Ethnic,American,Southwestern States");
	categoriesLIST.push("COOKING,Regional & Ethnic,American,Western States");
	categoriesLIST.push("COOKING,Regional & Ethnic,Asian");
	categoriesLIST.push("COOKING,Regional & Ethnic,British see Regional & Ethnic,English  Scottish & Welsh");
	categoriesLIST.push("COOKING,Regional & Ethnic,Cajun & Creole");
	categoriesLIST.push("COOKING,Regional & Ethnic,Canadian");
	categoriesLIST.push("COOKING,Regional & Ethnic,Caribbean & West Indian");
	categoriesLIST.push("COOKING,Regional & Ethnic,Central American & South American");
	categoriesLIST.push("COOKING,Regional & Ethnic,Chinese");
	categoriesLIST.push("COOKING,Regional & Ethnic,Creole see Regional & Ethnic,Cajun & Creole");
	categoriesLIST.push("COOKING,Regional & Ethnic,Eastern European see Regional & Ethnic,European");
	categoriesLIST.push("COOKING,Regional & Ethnic,English  Scottish & Welsh");
	categoriesLIST.push("COOKING,Regional & Ethnic,European");
	categoriesLIST.push("COOKING,Regional & Ethnic,French");
	categoriesLIST.push("COOKING,Regional & Ethnic,German");
	categoriesLIST.push("COOKING,Regional & Ethnic,Greek");
	categoriesLIST.push("COOKING,Regional & Ethnic,Hungarian");
	categoriesLIST.push("COOKING,Regional & Ethnic,Indian & South Asian");
	categoriesLIST.push("COOKING,Regional & Ethnic,International");
	categoriesLIST.push("COOKING,Regional & Ethnic,Irish");
	categoriesLIST.push("COOKING,Regional & Ethnic,Italian");
	categoriesLIST.push("COOKING,Regional & Ethnic,Japanese");
	categoriesLIST.push("COOKING,Regional & Ethnic,Jewish & Kosher");
	categoriesLIST.push("COOKING,Regional & Ethnic,Latin American see Regional & Ethnic,Central American & South American");
	categoriesLIST.push("COOKING,Regional & Ethnic,Mediterranean");
	categoriesLIST.push("COOKING,Regional & Ethnic,Mexican");
	categoriesLIST.push("COOKING,Regional & Ethnic,Middle Eastern");
	categoriesLIST.push("COOKING,Regional & Ethnic,Native American");
	categoriesLIST.push("COOKING,Regional & Ethnic,Pacific Rim");
	categoriesLIST.push("COOKING,Regional & Ethnic,Polish");
	categoriesLIST.push("COOKING,Regional & Ethnic,Portuguese");
	categoriesLIST.push("COOKING,Regional & Ethnic,Russian");
	categoriesLIST.push("COOKING,Regional & Ethnic,Scandinavian");
	categoriesLIST.push("COOKING,Regional & Ethnic,Scottish see Regional & Ethnic,English  Scottish & Welsh");
	categoriesLIST.push("COOKING,Regional & Ethnic,Soul Food");
	categoriesLIST.push("COOKING,Regional & Ethnic,South American see Regional & Ethnic,Central American & South American");
	categoriesLIST.push("COOKING,Regional & Ethnic,Spanish");
	categoriesLIST.push("COOKING,Regional & Ethnic,Thai");
	categoriesLIST.push("COOKING,Regional & Ethnic,Turkish");
	categoriesLIST.push("COOKING,Regional & Ethnic,Vietnamese");
	categoriesLIST.push("COOKING,Regional & Ethnic,Welsh see Regional & Ethnic,English  Scottish & Welsh");
	categoriesLIST.push("COOKING,Regional & Ethnic,West Indian see Regional & Ethnic,Caribbean & West Indian");
	categoriesLIST.push("COOKING,Seasonal");
	categoriesLIST.push("COOKING,Specific Ingredients,General");
	categoriesLIST.push("COOKING,Specific Ingredients,Dairy");
	categoriesLIST.push("COOKING,Specific Ingredients,Fruit");
	categoriesLIST.push("COOKING,Specific Ingredients,Game");
	categoriesLIST.push("COOKING,Specific Ingredients,Herbs  Spices  Condiments");
	categoriesLIST.push("COOKING,Specific Ingredients,Meat");
	categoriesLIST.push("COOKING,Specific Ingredients,Natural Foods");
	categoriesLIST.push("COOKING,Specific Ingredients,Pasta");
	categoriesLIST.push("COOKING,Specific Ingredients,Poultry");
	categoriesLIST.push("COOKING,Specific Ingredients,Rice & Grains");
	categoriesLIST.push("COOKING,Specific Ingredients,Seafood");
	categoriesLIST.push("COOKING,Specific Ingredients,Vegetables");
	categoriesLIST.push("COOKING,Tablesetting");
	categoriesLIST.push("COOKING,Vegetarian & Vegan");
	categoriesLIST.push("CRAFTS & HOBBIES,General");
	categoriesLIST.push("CRAFTS & HOBBIES,Applique");
	categoriesLIST.push("CRAFTS & HOBBIES,Baskets");
	categoriesLIST.push("CRAFTS & HOBBIES,Beadwork");
	categoriesLIST.push("CRAFTS & HOBBIES,Book Printing & Binding");
	categoriesLIST.push("CRAFTS & HOBBIES,Candle & Soap Making");
	categoriesLIST.push("CRAFTS & HOBBIES,Carving");
	categoriesLIST.push("CRAFTS & HOBBIES,Ceramics see Pottery & Ceramics");
	categoriesLIST.push("CRAFTS & HOBBIES,Crafts for Children");
	categoriesLIST.push("CRAFTS & HOBBIES,Decorating");
	categoriesLIST.push("CRAFTS & HOBBIES,Dollhouses");
	categoriesLIST.push("CRAFTS & HOBBIES,Dolls & Doll Clothing");
	categoriesLIST.push("CRAFTS & HOBBIES,Dough");
	categoriesLIST.push("CRAFTS & HOBBIES,Dye");
	categoriesLIST.push("CRAFTS & HOBBIES,Fashion");
	categoriesLIST.push("CRAFTS & HOBBIES,Felting *");
	categoriesLIST.push("CRAFTS & HOBBIES,Fiber Arts & Textiles *");
	categoriesLIST.push("CRAFTS & HOBBIES,Flower Arranging");
	categoriesLIST.push("CRAFTS & HOBBIES,Folkcrafts");
	categoriesLIST.push("CRAFTS & HOBBIES,Framing");
	categoriesLIST.push("CRAFTS & HOBBIES,Glass & Glassware");
	categoriesLIST.push("CRAFTS & HOBBIES,Graphic Arts see headings under DESIGN,Graphic Arts");
	categoriesLIST.push("CRAFTS & HOBBIES,Jewelry");
	categoriesLIST.push("CRAFTS & HOBBIES,Knots  Macrame & Rope Work");
	categoriesLIST.push("CRAFTS & HOBBIES,Leatherwork");
	categoriesLIST.push("CRAFTS & HOBBIES,Metal Work");
	categoriesLIST.push("CRAFTS & HOBBIES,Miniatures");
	categoriesLIST.push("CRAFTS & HOBBIES,Mixed Media");
	categoriesLIST.push("CRAFTS & HOBBIES,Model Railroading");
	categoriesLIST.push("CRAFTS & HOBBIES,Models");
	categoriesLIST.push("CRAFTS & HOBBIES,Nature Crafts");
	categoriesLIST.push("CRAFTS & HOBBIES,Needlework,General");
	categoriesLIST.push("CRAFTS & HOBBIES,Needlework,Crocheting");
	categoriesLIST.push("CRAFTS & HOBBIES,Needlework,Cross-Stitch");
	categoriesLIST.push("CRAFTS & HOBBIES,Needlework,Embroidery");
	categoriesLIST.push("CRAFTS & HOBBIES,Needlework,Felting see Felting");
	categoriesLIST.push("CRAFTS & HOBBIES,Needlework,Knitting");
	categoriesLIST.push("CRAFTS & HOBBIES,Needlework,Lace & Tatting");
	categoriesLIST.push("CRAFTS & HOBBIES,Needlework,Needlepoint");
	categoriesLIST.push("CRAFTS & HOBBIES,Needlework,Tatting see Needlework,Lace & Tatting");
	categoriesLIST.push("CRAFTS & HOBBIES,Origami");
	categoriesLIST.push("CRAFTS & HOBBIES,Painting");
	categoriesLIST.push("CRAFTS & HOBBIES,Papercrafts");
	categoriesLIST.push("CRAFTS & HOBBIES,Patchwork");
	categoriesLIST.push("CRAFTS & HOBBIES,Polymer Clay");
	categoriesLIST.push("CRAFTS & HOBBIES,Potpourri");
	categoriesLIST.push("CRAFTS & HOBBIES,Pottery & Ceramics");
	categoriesLIST.push("CRAFTS & HOBBIES,Printmaking");
	categoriesLIST.push("CRAFTS & HOBBIES,Puppets & Puppetry");
	categoriesLIST.push("CRAFTS & HOBBIES,Quilts & Quilting");
	categoriesLIST.push("CRAFTS & HOBBIES,Reference");
	categoriesLIST.push("CRAFTS & HOBBIES,Ribbon Work ");
	categoriesLIST.push("CRAFTS & HOBBIES,Rugs");
	categoriesLIST.push("CRAFTS & HOBBIES,Scrapbooking");
	categoriesLIST.push("CRAFTS & HOBBIES,Seasonal");
	categoriesLIST.push("CRAFTS & HOBBIES,Sewing");
	categoriesLIST.push("CRAFTS & HOBBIES,Stained Glass see Glass & Glassware");
	categoriesLIST.push("CRAFTS & HOBBIES,Stenciling");
	categoriesLIST.push("CRAFTS & HOBBIES,Stuffed Animals");
	categoriesLIST.push("CRAFTS & HOBBIES,Toymaking");
	categoriesLIST.push("CRAFTS & HOBBIES,Weaving");
	categoriesLIST.push("CRAFTS & HOBBIES,Wirework ");
	categoriesLIST.push("CRAFTS & HOBBIES,Wood Toys");
	categoriesLIST.push("CRAFTS & HOBBIES,Woodwork");

	var categoriesJSONLIST = {};
	for (var line in categoriesLIST) {
		var cats = categoriesLIST[line].split(",");
		if (categoriesJSONLIST[cats[0]] == undefined) {
			categoriesJSONLIST[cats[0]] = {}
		}

		if (cats.length > 1) {
			if (categoriesJSONLIST[cats[0]][cats[1]] == undefined) {
				categoriesJSONLIST[cats[0]][cats[1]] = new Array();
			}

			if (cats.length > 2) {
				categoriesJSONLIST[cats[0]][cats[1]].push(cats[2]);
			} else {
				categoriesJSONLIST[cats[0]][cats[1]].push('General');
			}
		}
	}

	return categoriesJSONLIST;
}